application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      az-aem-search-integration:
        license: Apache-2.0
        actions:
          aem-page-index-upload-doc:
            function: actions/aem-page-index-upload-doc/index.js
            web: 'no'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              AZURE_TENANT_ID: $AZURE_TENANT_ID
              AZURE_CLIENT_ID: $AZURE_CLIENT_ID
              AZURE_CLIENT_SECRET: $AZURE_CLIENT_SECRET
              AZURE_SEARCH_ENDPOINT: $AZURE_SEARCH_ENDPOINT
              AZURE_SEARCH_INDEX_NAME: $AZURE_SEARCH_INDEX_NAME
            annotations:
              require-adobe-auth: false
              final: true
          aem-page-index-delete-doc:
            function: actions/aem-page-index-delete-doc/index.js
            web: 'no'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              AZURE_TENANT_ID: $AZURE_TENANT_ID
              AZURE_CLIENT_ID: $AZURE_CLIENT_ID
              AZURE_CLIENT_SECRET: $AZURE_CLIENT_SECRET
              AZURE_SEARCH_ENDPOINT: $AZURE_SEARCH_ENDPOINT
              AZURE_SEARCH_INDEX_NAME: $AZURE_SEARCH_INDEX_NAME
            annotations:
              require-adobe-auth: false
              final: true
  events:
    registrations:
      Add AEM Page to Index:
        description: Upload a document to the search index index when a page is published.
        events_of_interest:
          - provider_metadata: aemsites
            event_codes:
              - aem.sites.page.published
        runtime_action: az-aem-search-integration/aem-page-index-upload-doc
      Delete AEM Page From The Index:
        description: Delete a document from the search index when a page is unpublished.
        events_of_interest:
          - provider_metadata: aemsites
            event_codes:
              - aem.sites.page.unpublished
        runtime_action: az-aem-search-integration/aem-page-index-delete-doc
